//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaUninove.Sistema.Queries.Read {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueriesConsulta {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueriesConsulta() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademiaUninove.Sistema.Queries.Read.QueriesConsulta", typeof(QueriesConsulta).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consultar dados do Aluno
        ///SELECT 
        ///	 A.CD_ALU &apos;Código&apos;
        ///	 ,A.CD_FUNC &apos;Código Instrutor&apos;
        ///	 ,F.NOME_FUNC &apos;Nome Instrutor&apos;
        ///	 ,A.NOME_ALU &apos;Aluno&apos;
        ///	 ,A.CPF_ALU &apos;CPF&apos;
        ///	 ,A.RG_ALU &apos;RG&apos;
        ///	 ,A.DT_NASC &apos;Data Nasc&apos;
        ///	 ,A.TEL_RES &apos;Tel Residencial&apos;
        ///	 ,A.TEL_CEL &apos;Tel Celular&apos;
        ///	 ,A.END_ALU &apos;Endereço&apos;
        ///	 ,A.CEP_ALU &apos;CEP&apos;
        ///	 ,A.CIDADE &apos;Cidade&apos;
        ///	 ,A.STATUS_ALU &apos;Status&apos;
        ///	 ,A.RESTRICAO &apos;Restrição&apos;
        ///	 ,A.OBJETIVO &apos;Objetivo&apos;
        ///
        ///FROM ALUNO A
        ///LEFT OUTER JOIN FUNCIONARIO F
        ///ON A.CD_FUNC = F.CD_FUNC
        ///
        ///.
        /// </summary>
        public static string qConsultaAluno {
            get {
                return ResourceManager.GetString("qConsultaAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta geral de aulas
        ///
        ///SELECT CD_AULA, NOME_AULA FROM AULA.
        /// </summary>
        public static string qConsultaAula {
            get {
                return ResourceManager.GetString("qConsultaAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta Cargo
        ///SELECT CD_CARGO as &apos;Código&apos;, NOME_CARGO as &apos;Cargo&apos;
        ///FROM CARGO
        ///
        ///.
        /// </summary>
        public static string qConsultaCargo {
            get {
                return ResourceManager.GetString("qConsultaCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta de de aulas dos instrutores
        ///
        ///
        ///SELECT FA.CD_FUNC_AULA &apos;Código&apos;
        ///	  ,FA.CD_FUNC &apos;Código Instrutor&apos;
        ///	  ,F.NOME_FUNC &apos;Instrutor&apos;
        ///	  ,FA.CD_AULA &apos;Código Aula&apos;
        ///	  ,A.NOME_AULA &apos;Mome Aula&apos;
        ///  FROM FUNC_AULA FA
        ///  LEFT OUTER JOIN FUNCIONARIO F
        ///  ON FA.CD_FUNC =F.CD_FUNC
        ///  LEFT OUTER JOIN AULA A
        ///  ON FA.CD_AULA = A.CD_AULA
        /// .
        /// </summary>
        public static string qConsultaFuncAula {
            get {
                return ResourceManager.GetString("qConsultaFuncAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /****** Script for SelectTopNRows command from SSMS  ******/
        ///SELECT F.CD_FUNC &apos;Código&apos;
        ///      ,F.CD_CARGO &apos;Código Cargo&apos;
        ///	  ,C.NOME_CARGO &apos;Cargo&apos;
        ///      ,F.NOME_FUNC &apos;Nome Funcionário&apos;
        ///      ,F.END_FUNC &apos;Endereço&apos;
        ///      ,F.CEP_FUNC &apos;CEP&apos;
        ///      ,F.CIDADE &apos;Cidade&apos;
        ///      ,F.TEL_RES &apos;Tel. Residencial&apos;
        ///      ,F.TEL_CEL &apos;Tel. Celular&apos;
        ///  FROM FUNCIONARIO F
        ///  LEFT OUTER JOIN CARGO C
        ///  ON F.CD_CARGO = C.CD_CARGO.
        /// </summary>
        public static string qConsultaFuncionario {
            get {
                return ResourceManager.GetString("qConsultaFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta de de aulas dos instrutores
        ///
        ///
        ///SELECT FA.CD_FUNC_AULA &apos;Código&apos;
        ///	  ,FA.CD_FUNC &apos;Código Instrutor&apos;
        ///	  ,F.NOME_FUNC &apos;Instrutor&apos;
        ///	  ,FA.CD_AULA &apos;Código Aula&apos;
        ///	  ,A.NOME_AULA &apos;Mome Aula&apos;
        ///  FROM FUNC_AULA FA
        ///  LEFT OUTER JOIN FUNCIONARIO F
        ///  ON FA.CD_FUNC =F.CD_FUNC
        ///  LEFT OUTER JOIN AULA A
        ///  ON FA.CD_AULA = A.CD_AULA
        /// .
        /// </summary>
        public static string qConsultaHoraAula {
            get {
                return ResourceManager.GetString("qConsultaHoraAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta de Horário
        ///
        ///SELECT
        ///	CD_HORARIO &apos;Código&apos;,
        ///	convert(varchar, DATA_HORARIO, 103) &apos;Data&apos;,
        ///	CONVERT(VARCHAR, HORA, 8) &apos;HORA&apos;
        ///
        ///FROM HORARIO.
        /// </summary>
        public static string qConsultaHorario {
            get {
                return ResourceManager.GetString("qConsultaHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consultar usuário e senha
        ///SELECT Usuario, Senha
        ///	From Login
        ///Where Usuario = &apos;{0}&apos;
        ///And Senha = &apos;{1}&apos;.
        /// </summary>
        public static string qLogin {
            get {
                return ResourceManager.GetString("qLogin", resourceCulture);
            }
        }
    }
}
