//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaUninove.Sistema.Queries.Delete {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueriesDelete {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueriesDelete() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademiaUninove.Sistema.Queries.Delete.QueriesDelete", typeof(QueriesDelete).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Comando para excluir registros da tabela ALUNO
        ///
        ///DELETE FROM ALUNO
        ///	WHERE CD_ALU = {0}.
        /// </summary>
        public static string qDeleteAluno {
            get {
                return ResourceManager.GetString("qDeleteAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Comando para excluir registros da tabela aula
        ///
        ///DELETE FROM AULA
        ///	WHERE CD_AULA = {0}.
        /// </summary>
        public static string qDeleteAula {
            get {
                return ResourceManager.GetString("qDeleteAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Excluindo o Registro de Cargo
        ///DELETE FROM CARGO
        ///WHERE CD_CARGO = {0}.
        /// </summary>
        public static string qDeleteCargo {
            get {
                return ResourceManager.GetString("qDeleteCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Excluir registro das fichas
        ///
        ///DELETE FROM FICHA_EXERCICOS
        ///WHERE CD_FICHA = {0}.
        /// </summary>
        public static string qDeleteFicha {
            get {
                return ResourceManager.GetString("qDeleteFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- eXCLUI O REGISTRO DA FREQUENCIA DO aluno
        ///
        ///DELETE FROM FREQUENCIA
        ///WHERE CD_FREQ = {0}.
        /// </summary>
        public static string qDeleteFrequencia {
            get {
                return ResourceManager.GetString("qDeleteFrequencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Comando para excluir registros da tabela FUNC_AULA
        ///
        ///DELETE FROM FUNC_AULA
        ///	WHERE CD_FUNC_AULA = {0}.
        /// </summary>
        public static string qDeleteFuncAula {
            get {
                return ResourceManager.GetString("qDeleteFuncAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Comando para excluir registros da tabela FUNCIONARIO
        ///
        ///DELETE FROM FUNCIONARIO
        ///	WHERE CD_FUNC = {0}.
        /// </summary>
        public static string qDeleteFuncionario {
            get {
                return ResourceManager.GetString("qDeleteFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Comando para excluir registros da tabela FUNC_AULA
        ///
        ///DELETE FROM HORA_AULA
        ///	WHERE CD_HORA_AULA = {0}.
        /// </summary>
        public static string qDeleteHoraAula {
            get {
                return ResourceManager.GetString("qDeleteHoraAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Excluindo o Registro de HORARIO
        ///DELETE FROM HORARIO
        ///WHERE CD_HORARIO = {0}.
        /// </summary>
        public static string qDeleteHorario {
            get {
                return ResourceManager.GetString("qDeleteHorario", resourceCulture);
            }
        }
    }
}
