﻿--Para criar o banco de dados
USE master
GO

-- Drop the database if it already exists
IF  EXISTS (
	SELECT name 
		FROM sys.databases 
		WHERE name = 'AcademiaUninove'
)
DROP DATABASE AcademiaUninove
GO

CREATE DATABASE AcademiaUninove
GO

USE AcademiaUninove

CREATE TABLE LOGIN (
  CODIGO INTEGER NOT NULL ,
  USUARIO VARCHAR(20) NULL,
  SENHA VARCHAR(8) NULL,
  TIPO_USUARIO VARCHAR(15) NULL,
  DATA_CRIACAO DATE NULL,
  CONSTRAINT CODIGO_PK PRIMARY KEY(CODIGO)
); --ok

CREATE TABLE HORARIO (
  CD_HORARIO INTEGER  NOT NULL ,
  DATA_HORARIO DATE NULL,
  HORA DATE NULL,
  CONSTRAINT CD_HORARIO_PK PRIMARY KEY(CD_HORARIO)
); -- ok

CREATE TABLE CARGO (
  CD_CARGO INTEGER NOT NULL ,
  NOME_CARGO VARCHAR(20) NULL,
  CONSTRAINT CD_CARGO_PK PRIMARY KEY(CD_CARGO)
); -- ok

CREATE TABLE AULA (
  CD_AULA INTEGER NOT NULL ,
  NOME_AULA VARCHAR(20) NULL,
  CONSTRAINT CD_AULA_PK PRIMARY KEY(CD_AULA)
); -- ok

CREATE TABLE FUNCIONARIO (
  CD_FUNC INTEGER NOT NULL,
  CD_CARGO INTEGER NOT NULL ,
  NOME_FUNC VARCHAR(45) NULL,
  END_FUNC VARCHAR(45) NULL,
  CEP_FUNC VARCHAR(10) NULL,
  CIDADE VARCHAR(20) NULL,
  TEL_RES VARCHAR(20) NULL,
  TEL_CEL VARCHAR(20) NULL,
  CONSTRAINT CD_FUNC_PK PRIMARY KEY(CD_FUNC),
  CONSTRAINT CD_CARGO_FK FOREIGN KEY(CD_CARGO) REFERENCES CARGO(CD_CARGO) 
); -- ok 

CREATE TABLE ALUNO (
  CD_ALU INTEGER NOT NULL ,
  CD_FUNC INTEGER NOT NULL,
  NOME_ALU VARCHAR(45) NOT NULL,
  CPF_ALU VARCHAR(20) NOT NULL,
  RG_ALU VARCHAR(15) NOT NULL,
  DT_NASC VARCHAR(10) NOT NULL,
  TEL_RES VARCHAR(20) NULL,
  TEL_CEL VARCHAR(20) NULL,
  END_ALU VARCHAR(45) NULL,
  CEP_ALU VARCHAR(10) NULL,
  CIDADE VARCHAR(20) NULL,
  STATUS_ALU CHAR NULL,
  RESTRICAO VARCHAR(255) NULL,
  OBJETIVO VARCHAR(20) NULL,
  CONSTRAINT CD_ALU_PK PRIMARY KEY(CD_ALU),
  CONSTRAINT CD_FUNC_ALUNO_FK FOREIGN KEY(CD_FUNC) REFERENCES FUNCIONARIO(CD_FUNC)
); -- ok 

CREATE TABLE FUNC_AULA (
  CD_FUNC_AULA INTEGER NOT NULL,
  CD_FUNC INTEGER NOT NULL,
  CD_AULA INTEGER NOT NULL,
  CONSTRAINT CD_FUNC_AULA_PK PRIMARY KEY(CD_FUNC_AULA),
  CONSTRAINT CD_FUNC_FUNC_AULA_FK FOREIGN KEY(CD_FUNC) REFERENCES FUNCIONARIO(CD_FUNC),
  CONSTRAINT CD_AULA_FUNC_FK FOREIGN KEY(CD_AULA) REFERENCES AULA(CD_AULA)
); --ok

CREATE TABLE HORA_AULA (
  CD_HORA_AULA INTEGER NOT NULL,
  CD_HORARIO INTEGER NOT NULL,
  CD_AULA INTEGER NOT NULL,
  CONSTRAINT CD_HORA_AULA_PK PRIMARY KEY(CD_HORA_AULA),
  CONSTRAINT CD_HORARIO_FK FOREIGN KEY(CD_HORARIO) REFERENCES HORARIO(CD_HORARIO),
  CONSTRAINT CD_AULA_FK FOREIGN KEY(CD_AULA) REFERENCES AULA(CD_AULA)
); -- ok

--parte 2

CREATE TABLE MEDIDAS (
  CD_MEDIDAS INTEGER NOT NULL ,
  CD_ALU INTEGER NOT NULL,
  DATA_MEDIDAS DATE NOT NULL,
  PESO DECIMAL(3,2),
  ABDOMEN DECIMAL(3,2),
  ANTEBRACO_DIR DECIMAL(3,2),
  ANTEBRACO_ESQ DECIMAL(3,2),
  BRACO_DIR DECIMAL(3,2),
  BRACO_ESQ DECIMAL(3,2),
  BUSTO DECIMAL(3,2),
  CINTURA DECIMAL(3,2),
  COXA_DIR DECIMAL(3,2),
  COXA_ESQ DECIMAL(3,2),
  OMBRO DECIMAL(3,2),
  PERNA_DIR DECIMAL(3,2),
  PERNA_ESQ DECIMAL(3,2),
  QUADRIL DECIMAL(3,2),
  TORAX DECIMAL(3,2),
  ALTURA DECIMAL(3,2),
  IMC DECIMAL(3,2),
  CONSTRAINT CD_MEDIDAS_PK PRIMARY KEY(CD_MEDIDAS),
  CONSTRAINT CD_ALU_MED_FK FOREIGN KEY(CD_ALU) REFERENCES ALUNO(CD_ALU)
); --ok

CREATE TABLE FICHA_EXERCICIOS (
  CD_FICHA INTEGER NOT NULL ,
  CD_ALU INTEGER NOT NULL,
  NM_EXERCICIO VARCHAR(25) NULL,
  REPETICOES VARCHAR(20) NULL,
  SERIES VARCHAR(10) NULL,
  TREINO VARCHAR(10) NULL,
  DATA_INICIO DATE NULL,
  CONSTRAINT CD_FICHA_PK PRIMARY KEY(CD_FICHA),
  CONSTRAINT CD_ALU_FICHA_FK FOREIGN KEY(CD_ALU) REFERENCES ALUNO(CD_ALU)
); --ok

CREATE TABLE FREQUENCIA (
  CD_FREQ INTEGER NOT NULL ,
  CD_ALU INTEGER NOT NULL,
  DATA_HORA DATE NULL,
  CONSTRAINT CD_FREQ_PK PRIMARY KEY(CD_FREQ),
  CONSTRAINT CD_ALU_FREQ_FK FOREIGN KEY(CD_ALU) REFERENCES ALUNO(CD_ALU)
); -- ok



