//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaUninove.Sistema.Queries.Update {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QueriesUpdate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueriesUpdate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademiaUninove.Sistema.Queries.Update.QueriesUpdate", typeof(QueriesUpdate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consultar dados do Aluno
        ///SELECT 
        ///	 A.CD_ALU &apos;Código&apos;
        ///	 ,A.CD_FUNC &apos;Código Instrutor&apos;
        ///	 ,F.NOME_FUNC &apos;Nome Instrutor&apos;
        ///	 ,A.NOME_ALU &apos;Aluno&apos;
        ///	 ,A.CPF_ALU &apos;CPF&apos;
        ///	 ,A.RG_ALU &apos;RG&apos;
        ///	 ,A.DT_NASC &apos;Data Nasc&apos;
        ///	 ,A.TEL_RES &apos;Tel Residencial&apos;
        ///	 ,A.TEL_CEL &apos;Tel Celular&apos;
        ///	 ,A.END_ALU &apos;Endereço&apos;
        ///	 ,A.CIDADE &apos;Cidade&apos;
        ///	 ,A.STATUS_ALU &apos;Status&apos;
        ///	 ,A.RESTRICAO &apos;Restrição&apos;
        ///	 ,A.OBJETIVO &apos;Objetivo&apos;
        ///
        ///FROM ALUNO A
        ///LEFT OUTER JOIN FUNCIONARIO F
        ///ON A.CD_FUNC = F.CD_FUNC
        ///
        ///WHERE A.CD_ALU = {0}.
        /// </summary>
        public static string qConsultaAlunoEdit {
            get {
                return ResourceManager.GetString("qConsultaAlunoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta de Horário para edição
        ///
        ///SELECT
        ///	CD_HORARIO &apos;Código&apos;,
        ///	DATA_HORARIO &apos;Data&apos;,
        ///	HORA &apos;Hora&apos;
        ///
        ///FROM HORARIO
        ///
        ///WHERE CD_HORARIO = {0}.
        /// </summary>
        public static string qConsultaAulaEdit {
            get {
                return ResourceManager.GetString("qConsultaAulaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta Cargo para Edição
        ///SELECT CD_CARGO as &apos;Código&apos;, NOME_CARGO as &apos;Cargo&apos;
        ///FROM CARGO
        ///
        ///where CD_CARGO = {0}
        ///
        ///.
        /// </summary>
        public static string qConsultaCargoEdit {
            get {
                return ResourceManager.GetString("qConsultaCargoEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string qConsultaFrequenciaEdit {
            get {
                return ResourceManager.GetString("qConsultaFrequenciaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta de de aulas dos instrutores
        ///
        ///
        ///SELECT FA.CD_FUNC_AULA &apos;Código&apos;
        ///	  ,FA.CD_FUNC &apos;Código Instrutor&apos;
        ///	  ,F.NOME_FUNC &apos;Instrutor&apos;
        ///	  ,FA.CD_AULA &apos;Código Aula&apos;
        ///	  ,A.NOME_AULA &apos;Mome Aula&apos;
        ///  FROM FUNC_AULA FA
        ///  LEFT OUTER JOIN FUNCIONARIO F
        ///  ON FA.CD_FUNC =F.CD_FUNC
        ///  LEFT OUTER JOIN AULA A
        ///  ON FA.CD_AULA = A.CD_AULA
        ///  WHERE 
        ///		FA.CD_FUNC = {0}.
        /// </summary>
        public static string qConsultaFuncAulaEdit {
            get {
                return ResourceManager.GetString("qConsultaFuncAulaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta de de aulas dos instrutores
        ///
        ///
        ///SELECT FA.CD_FUNC_AULA &apos;Código&apos;
        ///	  ,FA.CD_FUNC &apos;Código Instrutor&apos;
        ///	  ,F.NOME_FUNC &apos;Instrutor&apos;
        ///	  ,FA.CD_AULA &apos;Código Aula&apos;
        ///	  ,A.NOME_AULA &apos;Mome Aula&apos;
        ///  FROM FUNC_AULA FA
        ///  LEFT OUTER JOIN FUNCIONARIO F
        ///  ON FA.CD_FUNC =F.CD_FUNC
        ///  LEFT OUTER JOIN AULA A
        ///  ON FA.CD_AULA = A.CD_AULA
        ///  WHERE 
        ///		FA.CD_FUNC_AULA = {0}.
        /// </summary>
        public static string qConsultaFuncAulaEdit2 {
            get {
                return ResourceManager.GetString("qConsultaFuncAulaEdit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta de funcionários para edição
        ///
        ////****** Script for SelectTopNRows command from SSMS  ******/
        ///SELECT F.CD_FUNC &apos;Código&apos;
        ///      ,F.CD_CARGO &apos;Código Cargo&apos;
        ///	  ,C.NOME_CARGO &apos;Cargo&apos;
        ///      ,F.NOME_FUNC &apos;Nome Funcionário&apos;
        ///      ,F.END_FUNC &apos;Endereço&apos;
        ///      ,F.CEP_FUNC &apos;CEP&apos;
        ///      ,F.CIDADE &apos;Cidade&apos;
        ///      ,F.TEL_RES &apos;Tel. Residencial&apos;
        ///      ,F.TEL_CEL &apos;Tel. Celular&apos;
        ///  FROM FUNCIONARIO F
        ///  LEFT OUTER JOIN CARGO C
        ///  ON F.CD_CARGO = C.CD_CARGO
        ///  WHERE 
        ///		F.CD_FUNC = {0}.
        /// </summary>
        public static string qConsultaFuncionarioEdit {
            get {
                return ResourceManager.GetString("qConsultaFuncionarioEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta de horas aulas
        ///
        ///
        ///SELECT 
        ///	HA.CD_HORA_AULA &apos;Código&apos;,
        ///	HA.CD_HORARIO &apos;Código Horário&apos;,
        ///	H.DATA_HORARIO &apos;Horário&apos;,
        ///	HA.CD_AULA &apos;Código Aula&apos;,
        ///	A.NOME_AULA &apos;Nome Aula&apos;
        ///FROM HORA_AULA HA
        ///LEFT OUTER JOIN HORARIO H
        ///ON HA.CD_HORARIO = H.CD_HORARIO
        ///LEFT OUTER JOIN AULA A
        ///ON HA.CD_AULA = A.CD_AULA
        ///
        ///WHERE HA.CD_HORA_AULA  = {0}.
        /// </summary>
        public static string qConsultaHoraAulaEdit {
            get {
                return ResourceManager.GetString("qConsultaHoraAulaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta de horas aulas
        ///
        ///
        ///SELECT 
        ///	HA.CD_HORA_AULA &apos;Código&apos;,
        ///	HA.CD_HORARIO &apos;Código Horário&apos;,
        ///	H.DATA_HORARIO &apos;Horário&apos;,
        ///	HA.CD_AULA &apos;Código Aula&apos;,
        ///	A.NOME_AULA &apos;Nome Aula&apos;
        ///FROM HORA_AULA HA
        ///LEFT OUTER JOIN HORARIO H
        ///ON HA.CD_HORARIO = H.CD_HORARIO
        ///LEFT OUTER JOIN AULA A
        ///ON HA.CD_AULA = A.CD_AULA
        ///
        ///WHERE HA.CD_HORA_AULA  = {0}.
        /// </summary>
        public static string qConsultaHoraAulaEdit2 {
            get {
                return ResourceManager.GetString("qConsultaHoraAulaEdit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Consulta horario para Edição
        ///-- Consulta de Horário
        ///
        ///SELECT
        ///	CD_HORARIO &apos;Código&apos;,
        ///	convert(varchar, DATA_HORARIO, 103) &apos;Data&apos;,
        ///	CONVERT(VARCHAR, HORA, 8) &apos;HORA&apos;
        ///
        ///FROM HORARIO
        ///    WHERE CD_HORARIO = {0}.
        /// </summary>
        public static string qConsultaHorarioEdit {
            get {
                return ResourceManager.GetString("qConsultaHorarioEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Comando de update aluno
        ///
        ///UPDATE ALUNO 
        ///SET 
        ///	CD_FUNC = {1},
        ///	NOME_ALU = &apos;{2}&apos;,
        ///	CPF_ALU = &apos;{3}&apos;,
        ///	RG_ALU = &apos;{4}&apos;,
        ///	DT_NASC = &apos;{5}&apos;,
        ///	TEL_RES = &apos;{6}&apos;,
        ///	TEL_CEL = &apos;{7}&apos;,
        ///	END_ALU = &apos;{8}&apos;,
        ///	CEP_ALU = &apos;{9}&apos;,
        ///	CIDADE = &apos;{10}&apos;,
        ///	STATUS_ALU = &apos;{11}&apos;,
        ///	RESTRICAO = &apos;{12}&apos;,
        ///	OBJETIVO = &apos;{13}&apos;
        ///WHERE
        ///	CD_ALU = {0}
        ///	.
        /// </summary>
        public static string qUpdateAluno {
            get {
                return ResourceManager.GetString("qUpdateAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Comando de update aula
        ///
        ///UPDATE AULA SET NOME_AULA = &apos;{0}&apos;
        ///WHERE CD_AULA = {1}.
        /// </summary>
        public static string qUpdateAula {
            get {
                return ResourceManager.GetString("qUpdateAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Atualizando cargo
        ///
        ///UPDATE CARGO SET NOME_CARGO = &apos;{0}&apos;
        ///WHERE CD_CARGO = {1}.
        /// </summary>
        public static string qUpdateCargo {
            get {
                return ResourceManager.GetString("qUpdateCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string qUpdateFrequencia {
            get {
                return ResourceManager.GetString("qUpdateFrequencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Comando de update aula dos instrutores
        ///
        ///UPDATE FUNC_AULA 
        ///SET 
        ///		CD_FUNC = {1}
        ///		,CD_AULA = {2}	
        ///WHERE
        ///		CD_FUNC_AULA = {0}.
        /// </summary>
        public static string qUpdateFuncAula {
            get {
                return ResourceManager.GetString("qUpdateFuncAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Comando de update FUNCIONÁRIO
        ///
        ///UPDATE FUNCIONARIO 
        ///SET 
        ///		CD_CARGO = {1}
        ///		,NOME_FUNC = &apos;{2}&apos;
        ///		,END_FUNC = &apos;{3}&apos;
        ///		,CEP_FUNC = &apos;{4}&apos;
        ///		,CIDADE = &apos;{5}&apos;
        ///		,TEL_RES = &apos;{6}&apos;
        ///		,TEL_CEL = &apos;{7}&apos;
        ///WHERE
        ///		CD_FUNC = {0}.
        /// </summary>
        public static string qUpdateFuncionario {
            get {
                return ResourceManager.GetString("qUpdateFuncionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Comando de update aula dos instrutores
        ///
        ///UPDATE HORA_AULA 
        ///SET 
        ///		CD_HORARIO = {1}
        ///		,CD_AULA = {2}	
        ///WHERE
        ///		CD_HORA_AULA = {0}.
        /// </summary>
        public static string qUpdateHoraAula {
            get {
                return ResourceManager.GetString("qUpdateHoraAula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Atualizando HORARIO
        ///
        ///UPDATE HORARIO
        ///SET 	
        ///	DATA_HORARIO = &apos;{0}&apos;,
        ///	HORA = &apos;{1}&apos;
        ///
        ///WHERE CD_HORARIO = {2}.
        /// </summary>
        public static string qUpdateHorario {
            get {
                return ResourceManager.GetString("qUpdateHorario", resourceCulture);
            }
        }
    }
}
